version: "3"
services:
  backend:
    build: .
    image: nattapat34/my-app-backend:lastest
    ports:
      - "8088:80"
    container_name: fast-api_container
  frontend:
    build: ./frontend
    image: nattapat34/my-app-frontend:latest
    ports:
      - "5000:3000"
    container_name: frontend_container